# Generated by Django 3.0.8 on 2020-12-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201218_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
