# Generated by Django 3.0.8 on 2020-12-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201229_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='posts_images/'),
        ),
    ]
