# Generated by Django 3.0.8 on 2020-12-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_likes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(default='default-profile-pic.png', upload_to='profile_pics'),
        ),
    ]
