# Generated by Django 3.0.8 on 2020-12-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='profile_pic',
        ),
    ]
