# Generated by Django 3.0.8 on 2021-08-05 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210804_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='desciption',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
