# Generated by Django 3.0.8 on 2021-08-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210805_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desciption',
            new_name='description',
        ),
    ]
