# Generated by Django 3.0.8 on 2021-01-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210102_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
